In [1]:
import numpy as np
from scipy.optimize import minimize

# Define the problem matrices
P = np.array([[4, 1], [1, 2]])
q = np.array([1, 1])
A = np.array([[1, 1], [1, 0], [0, 1]])
l = np.array([1, 0, 0])
u = np.array([1, 0.7, 0.7])

# Define the objective function and constraints
def objective(x):
  return 0.5 * x.T @ P @ x + q @ x

def constraint1(x):
  return x[0] - x[1] - 1

def constraint2(x):
  return 1 - x[0]

def constraint3(x):
  return 1 - x[1]

con1 = {'type': 'ineq', 'fun': constraint1}
con2 = {'type': 'ineq', 'fun': constraint2}
con3 = {'type': 'ineq', 'fun': constraint3}
cons = [con1, con2, con3]

# Solve the QP problem
solution = minimize(objective, x0=np.zeros(2), method='SLSQP', constraints=cons)

# Print the optimal solution and objective value
print(f"optimal x: {solution.x}")
print(f"optimal obj: {solution.fun}")


optimal x: [ 0.12499999 -0.87500001]
optimal obj: -0.06250000000445632


In [8]:
import numpy as np
def factorial(n,r):
    '''
    n is the number of parameters
    r is the derivative order
    '''
    if (n < r):
        return 0
    ans = 1
    for _ in range(r):
        ans = ans*n
        n -= 1
        
    return ans

In [12]:
n = 6
Q = np.zeros((n,n))
r = 3
for i in range(n):
    for j in range(n):
        if i >= r and j >= r:
            Q[n-1-i][n-1-j] = factorial(i,r)*factorial(j,r)/(i+j-2*r+1)

print(Q)

[[720. 360. 120.   0.   0.   0.]
 [360. 192.  72.   0.   0.   0.]
 [120.  72.  36.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]


In [17]:
array = np.array([[1,2,3],[2,3,1]])
print(array[0][0])

1
