In [1]:
import numpy as np
def CompurteQ(n,r,ts,te):
    '''
    args:
        n is the number of parameters
        r is the derivative order
        ts is the start time of this segment
        te is the end time of this segment
    return:
        one segment Q matrix of QP.
    '''
    Q = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            if i >= r and j >= r:
                factor = i+j-2*r+1
                Q[n-1-i][n-1-j] = factorial(i,r)*factorial(j,r)/factor*(te**factor-ts**factor)
    return Q

def factorial(n,r):
    '''
    return A_n^(n-r)
    '''
    if (n < r):
        return 0
    ans = 1
    for _ in range(r):
        ans = ans*n
        n -= 1
        
    return ans

In [2]:
n = 6
r = 3
ts = 0
te = 1
print(CompurteQ(n,r,ts,te))

[[720. 360. 120.   0.   0.   0.]
 [360. 192.  72.   0.   0.   0.]
 [120.  72.  36.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
